"""Adicionando tabelas

Revision ID: 61a561cf387e
Revises: 
Create Date: 2026-04-29 15:29:11.442327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a561cf387e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senhaHash', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('submissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_coordenador', sa.Integer(), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_coordenador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissao')
    op.drop_table('usuario')
    # ### end Alembic commands ###
