"""Adicionando tabelas

Revision ID: b003077305c3
Revises: 
Create Date: 2026-05-02 16:38:50.731937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b003077305c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regra_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('limite_horas', sa.Integer(), nullable=False),
    sa.Column('requisito', sa.String(length=100), nullable=False),
    sa.Column('exige_certificado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('submissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_coordenador', sa.Integer(), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_coordenador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissao')
    op.drop_table('usuario')
    op.drop_table('regra_atividade')
    op.drop_table('curso')
    # ### end Alembic commands ###
