"""Adicionando tabela submissao e alteracoes nas outras tabelas

Revision ID: 332573b2fe28
Revises: e2d668bd28f6
Create Date: 2026-04-05 21:35:28.126070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '332573b2fe28'
down_revision = 'e2d668bd28f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordenador_curso',
    sa.Column('id_coordenador', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_coordenador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id_coordenador', 'id_curso')
    )
    op.create_table('submissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_coordenador', sa.Integer(), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_coordenador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('matricula',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    op.drop_table('submissao')
    op.drop_table('coordenador_curso')
    # ### end Alembic commands ###
